//
//  Contact.swift
//  contactsmanager
//
//  Created by alex on 14/3/2025.
//

import Foundation
import FirebaseFirestore

class Contact {
    var id : String!
    var firstname : String
    var lastname : String
    var email : String
    var phone : String
    var photo : String
    var note : String
    var favourite : Bool
    var registered : Timestamp
    var tags : [String]
    
    //Default initializer used whenever we want to create a Contact, and therefore we won't know the ID beforehand, it will be autogenerated by Firestore
    init(firstname: String, lastname: String, email: String, phone: String, photo: String, note: String, favourite: Bool, registered: Timestamp, tags: [String]) {
        self.firstname = firstname
        self.lastname = lastname
        self.email = email
        self.phone = phone
        self.photo = photo
        self.note = note
        self.favourite = favourite
        self.registered = registered
        self.tags = tags
    }
    //This initializer is used whenever we query the database
    convenience init(id : String, firstname: String, lastname: String, email: String, phone: String, photo: String, note: String, favourite: Bool, registered: Timestamp, tags: [String]) {
        
        self.init(firstname: firstname,
             lastname: lastname,
             email: email,
             phone: phone,
             photo: photo,
             note: note,
             favourite: favourite,
             registered: registered,
             tags: tags)
        self.id = id
    }
    
    //This initializer will be used whenever we want to fetch a contact from the database by Id
    convenience init(id: String) {
        self.init(firstname: "",
                  lastname: "",
                  email: "",
                  phone: "",
                  photo: "",
                  note: "",
                  favourite: false,
                  registered: Timestamp(date: Date()),
                  tags: [String]() )
        self.id = id
    }
    //firestore returns dictionaries
    convenience init(id : String, dictionary : [String: Any]) {
        self.init(id: id,
                  firstname: dictionary["firstname"] as? String ?? "",
                  lastname: dictionary["lastname"] as? String ?? "",
                  email: dictionary["email"] as? String ?? "",
                  phone: dictionary["phone"] as? String ?? "",
                  photo: dictionary["photo"] as? String ?? "",
                  note: dictionary["note"] as? String ?? "",
                  favourite: dictionary["favourite"] as? Bool ?? false,
                  registered: dictionary["registered"] as? Timestamp ?? Timestamp(date: Date()),
                  tags: dictionary["tags"] as? [String] ?? [String]()
                  )
    }
    
    func toString() -> String {
            return "id: \(id ?? "NO AUTOID"), firstname: \(firstname), lastname: \(lastname), email: \(email), phone: \(phone), photo: \(photo), favourite \(favourite), note: \(note), registered: \(registered)"
        }
    
}
